name: Hello World on Release

on:
  release:
    types: [published]
  push:

env:
  MESSAGE: "Hello World"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Info
      run: echo ${{ env.MESSAGE }}
