name: Hello World on Release

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      inputsEnv: ${{ inputs }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Hello_World
      run: echo Hello_World

    - name: Hello_World
      run: "echo '${{env.inputsEnv}}'"
