name: Hello World on Release

on: release
env:
  inputsEnv: ${{ inputs }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Hello_World
      run: echo Hello_World

    - name: Hello_World
      run: "echo '${{env.inputsEnv}}'"
